select * from customer limit 20;
-- Q1. Total Revenue Generated by Male vs Female ?

select gender,sum(purchase_amount)as Revenue
from customer
group by gender
order by revenue desc;

-- Q2. Which Customer used discount but still spent more than the avg purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and
purchase_amount >(select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with highest avg review ratings?

select item_purchased as item,
round(avg(review_rating)::numeric,2) as rating -- Numeric is used to convert czz in pgsql the round is not used for int,float
from customer 
group by item
order by rating desc
limit 5;

-- Q4. Compare the avg Purchase Amount b/w Standard and Express Shipping ?

select shipping_type as shipping , 
round(avg(purchase_amount),2) as Avg_Purchase
from customer 
where shipping_type in ('Express','Standard')
group by shipping;

-- Q5. Do subscribed customers spend more? Compare avg spend and total revenue b/w 
-- subscribers and non-sunscribers

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as Avg_Amount,
round(sum(purchase_amount),2)as Revenue
from customer
group by subscription_status
order by Avg_Amount,Revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied ?

select item_purchased as item,
round(100* sum(case 
		when discount_applied = 'Yes' THEN 1 
		ELSE 0
	END
)/count(*),2) as discount_rate
from customer 
group by item
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning & Loyal based on their total no of purchase
-- & show the count of each segment ?

with customer_type as 
(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN  previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer)

select customer_segment,count(*) as "No of Customers"
from customer_type 
group by customer_segment;

-- Q8. Top 3 products from each category whose purchase is more ?

with item_count as 
(
	select category,item_purchased,
 	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id)desc) as item_rank
	from customer
	group by category,item_purchased
 
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_customers
from customer
where previous_purchases >5
group by subscription_status;

--Q10. What is the revenue contibution of each age_group ?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;


